Task 1

In [2]:
def div_by_zero():
 return 5/0
try:
 div_by_zero()
except ZeroDivisionError as e:
 print("Handle run-time 'div by 0'error:", e)

Handle run-time 'div by 0'error: division by zero


Task 2

In [1]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Task 3

In [3]:
def vander_Input(x,N,order):
    X=x.size
    result_array=np.empty((N,X),dtype=int)
    
    if order.upper()=="TRUE":
        for i in range(N):
            power_vector=np.array(np.power(x,i))
            result_array[i]=power_vector
    else:
        for i in range(N-1,-1,-1):
            power_vector=np.array(np.power(x,i))
            result_array[(N-1)-i]=power_vector
    return result_array

In [4]:
import numpy as np
print('Generate a Vandermonde matrix...')

N=int(input('Enter the value of N power :'))

print('Enter comma separated list of elements eg. 1,2,3 :')
input_vector=input()
input_list=list(map(int,input_vector.split(',')))
x=np.array(input_list)
print('Input vector is :')
print(x)

order=input("Enter 'True' for increasing order of powers else enter 'False' :")

result_array=vander_Input(x,N,order)
print('The resultant Vandermonde matrix is :')
print(result_array.T)

Generate a Vandermonde matrix...
Enter the value of N power :3
Enter comma separated list of elements eg. 1,2,3 :
1,2,3
Input vector is :
[1 2 3]
Enter 'True' for increasing order of powers else enter 'False' :True
The resultant Vandermonde matrix is :
[[1 1 1]
 [1 2 4]
 [1 3 9]]
